/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2hernandezgabriel.Ventanas;

import proyecto2hernandezgabriel.Aminoacido;
import proyecto2hernandezgabriel.ArbolBB;
import proyecto2hernandezgabriel.FragmentoADN;
import proyecto2hernandezgabriel.TablaHash;

/**
 *
 * @author gabriel
 */
public class ListaAminoacidos extends javax.swing.JFrame {

    public static ArbolBB arbol;
    public static TablaHash tabla;

    /**
     * Creates new form MenuPrincipal
     */
    public ListaAminoacidos(ArbolBB a, TablaHash t) {
        arbol = a;
        tabla = t;
        initComponents();
        this.setVisible(true);
        this.jTextArea1.setText(this.listarAminoacidos());

    }

    public String listarAminoacidos() {
        StringBuilder resultado = new StringBuilder();
        Aminoacido[] aminoacidos = obtenerAminoacidos();
        for (Aminoacido aminoacido : aminoacidos) {
            boolean hayTripletas = false;
            for (String fragmento : aminoacido.fragmentos) {
                FragmentoADN f = tabla.buscar(fragmento);
                if (f != null && f.getFrec() > 0) {
                    if (!hayTripletas) {
                        resultado.append("Aminoácido: ").append(aminoacido.abv1).append(" (").append(aminoacido.abv2).append(")\n");
                        hayTripletas = true;
                    }
                    resultado.append("  Tripleta: ").append(f.getFrag()).append(", Frecuencia: ").append(f.getFrec()).append("\n");
                }
            }
        }
        return resultado.toString();
    }

    private Aminoacido[] obtenerAminoacidos() {
        return new Aminoacido[]{
            new Aminoacido(new String[]{"UUU", "UUC"}, "Phe", "F"),
            new Aminoacido(new String[]{"UUA", "UUG"}, "Leu", "L"),
            new Aminoacido(new String[]{"UCU", "UCC", "UCA", "UCG"}, "Ser", "S"),
            new Aminoacido(new String[]{"UAU", "UAC"}, "Tyr", "Y"),
            new Aminoacido(new String[]{"UAA", "UAG"}, "Stop", "O"),
            new Aminoacido(new String[]{"UGU", "UGC"}, "Cys", "C"),
            new Aminoacido(new String[]{"UGA"}, "Stop", "O"),
            new Aminoacido(new String[]{"UGG"}, "Trp", "W"),
            new Aminoacido(new String[]{"CUU", "CUC", "CUA", "CUG"}, "Leu", "L"),
            new Aminoacido(new String[]{"CCU", "CCC", "CCA", "CCG"}, "Pro", "P"),
            new Aminoacido(new String[]{"CAU", "CAC"}, "His", "H"),
            new Aminoacido(new String[]{"CAA", "CAG"}, "Gln", "Q"),
            new Aminoacido(new String[]{"CGU", "CGC", "CGA", "CGG"}, "Arg", "R"),
            new Aminoacido(new String[]{"AUU", "AUC", "AUA"}, "Ile", "I"),
            new Aminoacido(new String[]{"AUG"}, "Met", "M"),
            new Aminoacido(new String[]{"ACU", "ACC", "ACA", "ACG"}, "Thr", "T"),
            new Aminoacido(new String[]{"AAU", "AAC"}, "Asn", "N"),
            new Aminoacido(new String[]{"AAA", "AAG"}, "Lys", "K"),
            new Aminoacido(new String[]{"GAU", "GAC"}, "Asp", "D"),
            new Aminoacido(new String[]{"GAA", "GAG"}, "Glu", "E"),
            new Aminoacido(new String[]{"GUU", "GUC", "GUA", "GUG"}, "Val", "V"),
            new Aminoacido(new String[]{"GCU", "GCC", "GCA", "GCG"}, "Ala", "A"),
            new Aminoacido(new String[]{"GGU", "GGC", "GGA", "GGG"}, "Gly", "G")
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 940, 380));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("LISTA DE AMINOACIDOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 51));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        MenuPrincipal m = new MenuPrincipal(arbol, tabla);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAminoacidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAminoacidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAminoacidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAminoacidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAminoacidos(arbol, tabla).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
